---
# caller-workflow.yml

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
    branches:
      - master
      - main

jobs:
  call-packer-validate:
    uses: opendaylight/releng-sandbox/.github/workflows/reusable-workflow-packer-validate.yml@master
    secrets:
      ENV_SECRETS: |
        CLOUDS_ENV_2XB64=${{ secrets.CLOUDS_ENV_2XB64 }}
        CLOUDS_YAML_2XB64=${{ secrets.CLOUDS_YAML_2XB64 }}
      JSON_SECRETS: ${{ toJSON(secrets) }}
