---
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 The Linux Foundation <abelur@linux.com>

name: "Call Github2Gerrit reusable workflow"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - master
      - main

jobs:
  call-in-g2g-workflow:
    permissions:
      contents: read
      pull-requests: write
    uses: askb/Github2Gerrit/.github/workflows/github2gerrit.yaml@main
    secrets: inherit
    with:
      gerrit_knwown_hosts: ${{ vars.GERRIT_KNOWN_HOSTS }}
      gerrit_ssh_user_g2g: ${{ vars.GERRIT_SSH_USER_G2G }}
      source_repo: ${{ github.repository }}
